### ISSUE TITLE
Add JSON.stringify

### ISSUE THREAD

**Issue by appsforartists** [sdras/object-explorer#14]

**Comment by xgebi** [comment]
May I ask why? JSON and object’s functions are two different things. Argumenting with JSON.stringify() and JSON.parse() would be better but ‘builtin objects explorer’ would be imho better place for this.

**Comment by nicolo-ribaudo** [comment]
I think that at least it should be mentioned in Object.toString(), since a when I want a string representation of `{a: 2}` I usually expect `"{ a: 2 }"`, not `[object Object]`.

**Comment by sdras** [comment]
Yeah, this doesn't actually qualify as an object method but it would be a nice thing to mention for people in `toString`, just to be helpful. @appsforartists brought it up on twitter and I asked that he make an issue for it. Probably could have used a description.

**Comment by appsforartists** [comment]
Sorry - my issue descriptions get lazy at 2AM. 😝

**Comment by sdras** [comment]
No worries! I knew what you meant :)

**Comment by appsforartists** [comment]
😃

**Comment by sdras** [comment]
fixed!
