### ISSUE TITLE
Objec.isSealed example is misleading

### ISSUE THREAD

**Issue by nicolo-ribaudo** [sdras/object-explorer#20]
```js
let obj = {
  a: 1,
  b: 2,
  c: 3
};

Object.defineProperty(obj, 'a', {
  configurable: false
})

console.log(Object.isSealed(obj)); // false
console.log(Object.isSealed(obj.a)); // true
```

Initially I thoght that `Object.isSealed(obj.a)` checked if the `a` property of `obj` is not configurable, but it returns true just because `obj.a` is not an object. A good example would actually seal `obj`.

---

EDIT:
Also the description isn't very clear:
> Determines if an object or its properties are sealed.

What does it mean that "its properties are sealed"? WDYT about "Determines if the descriptor of its properties can't be changed and new properties can't be created"?

**Comment by sdras** [comment]
Ah good point, I'll update this. Thanks

**Comment by Gonzalo2310** [comment]
This changes all the translations, right?

**Comment by nicolo-ribaudo** [comment]
Yes 👍

**Comment by Gonzalo2310** [comment]
thx
