### ISSUE TITLE
Additional note for beginners at Object.is

### ISSUE THREAD

**Issue by AWolf81** [sdras/object-explorer#4]
I think it would be good to add a beginners note to tripple equal comparison at `Object.is`.
Because most of the time `===` can be used instead of `Object.is`.

Also mentioned at MDN [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#When_to_use_Object.is_versus_triple_equals).

Just a small improvement but I really like the other beginners notes as they're really helpful.

**Comment by sdras** [comment]
Good idea. I like it. 👍

**Comment by sdras** [comment]
Fixed!
