### ISSUE TITLE
Object.create example output might be misleading

### ISSUE THREAD

**Issue by sandrosc** [sdras/object-explorer#44]
The `Object.create()` example shows the creation of a new object using `obj` as prototype. As output, a copy of `obj` is shown:
![image](https://user-images.githubusercontent.com/12650063/61243328-f9faf180-a747-11e9-9a9a-cda1a277e1b7.png)

While the properties are of course still accessible through the prototype chain, it might be a good idea to explicitly show the `__proto__` property, like chrome does:
![image](https://user-images.githubusercontent.com/12650063/61243357-0ed78500-a748-11e9-99af-be530f962550.png)

**Comment by sdras** [comment]
Hm, I think that might be too confusing for beginners, which is the point of this resource. Thanks though!
