### ISSUE TITLE
Change object.create note

### ISSUE THREAD

**Issue by nicolo-ribaudo** [sdras/object-explorer#7]
> *Important note for beginners!* It's more common to create an object the way that it's shown at the top of the example, by assigning it to a variable.

Also `var obj = Object.create(prototype)` is assigned to a variable :stuck_out_tongue:

**Comment by sdras** [comment]
This seems a little pedantic to me :) but ok, I'll change the wording here.

**Comment by nicolo-ribaudo** [comment]
Yeah, after looking at the site it isn't as confusing as I thought. I just got confused while translating it because I didn't see the full example.
Anyway, I think that `using braces` is clearer.

**Comment by sdras** [comment]
yep, agreed :)

**Comment by sdras** [comment]
Fixed!
